AWSTemplateFormatVersion: '2010-09-09'
Description: The template used to create an ECS Cluster from the ECS Console.

Parameters:
  ECSClusterName:
    Type: String
    Description: Specifies the ECS Cluster Name with which the resources would be associated
    Default: ECS-Cluster
  Namespace:
    Type: String
    Description: Namespace for ServiceConnectDefaults
    Default: Dev
  TaskDefinitionFamily:
    Type: String
    Description: Family for the ECS Task Definition
    Default: Task1-nginx
  ContainerName:
    Type: String
    Description: Name for the container
    Default: nginx
  ContainerImage:
    Type: String
    Description: Docker image for the container
    Default: nginx

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Ref ECSClusterName
      CapacityProviders:
        - FARGATE
        - FARGATE_SPOT
      ClusterSettings:
        - Name: containerInsights
          Value: disabled
      Configuration:
        ExecuteCommandConfiguration:
          Logging: DEFAULT
      ServiceConnectDefaults:
        Namespace: !Ref Namespace
      Tags: []

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Ref TaskDefinitionFamily
      Cpu: 1024
      Memory: 3072
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: arn:aws:iam::038629069022:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: !Ref ContainerName
          Image: !Ref ContainerImage
          Cpu: 0
          Memory: 1024
          PortMappings:
            - ContainerPort: 80
              HostPort: 80
              Protocol: tcp
          Essential: true
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-create-group: "true"
              awslogs-group: !Sub "/ecs/${TaskDefinitionFamily}"
              awslogs-region: !Ref "AWS::Region"
              awslogs-stream-prefix: "ecs"

Outputs:
  ECSCluster:
    Description: The created cluster.
    Value: !Ref ECSCluster
